"""
Configuration for the Maki Newsletter application.
Edit this file to change the topics, sources, LLM model, and output settings.
"""

import os

from dotenv import load_dotenv

load_dotenv()

# ---------------------------------------------------------------------------
# RSS feed sources — queried directly, no search engine required
# ---------------------------------------------------------------------------

RSS_FEEDS = {
    "TechCrunch":   "https://techcrunch.com/feed/",
    "Wired":        "https://www.wired.com/feed/rss",
    "Ars Technica": "https://feeds.arstechnica.com/arstechnica/index",
    "TechRadar":    "https://www.techradar.com/rss",
    "Gizmodo":      "https://gizmodo.com/rss",
    "HackerNews":   "https://news.ycombinator.com/rss",
    "CoinDesk":     "https://www.coindesk.com/arc/outboundfeeds/rss",
    "Fortune":      "https://fortune.com/feed/",
}

# ---------------------------------------------------------------------------
# Search / ranking
# ---------------------------------------------------------------------------

# Topic queries used to search HackerNews and as keyword hints for RSS
SEARCH_QUERIES = [
    "artificial intelligence latest research 2026",
    "cyber security vulnerabilities",
    "software engineering best practices",
    "cloud infrastructure devops",
    "open source new releases",
    "programming languages updates",
]

# Maximum article candidates before ranking
MAX_CANDIDATES = 50

# Number of articles in the final newsletter
TOP_N = 50

# Max articles fetched per RSS feed
MAX_PER_FEED = 10

# Max HackerNews results per query
MAX_HN_PER_QUERY = 5

# ---------------------------------------------------------------------------
# LLM
# ---------------------------------------------------------------------------

LLM_MODEL = "gemma4:26b"
#LLM_MODEL = "qwen3.6:27b"
OLLAMA_HOST = "http://localhost:11434"

# Characters sent to the LLM per article (prevents context overflow)
MAX_ARTICLE_CHARS = 10000

# Preferred word range for each short article summary. The pipeline still keeps
# summaries to exactly 2 sentences, but this tighter range helps article blurbs
# feel visually and editorially consistent across the newsletter.
SUMMARY_MIN_WORDS = 35
SUMMARY_MAX_WORDS = 48

# ---------------------------------------------------------------------------
# Trend cross-checking
# ---------------------------------------------------------------------------

# Seed keywords sent to Google Trends (max 5 per batch; batched automatically)
TREND_SEED_KEYWORDS = [
    "artificial intelligence",
    "cybersecurity",
    "blockchain",
    "information technology",
    "bitcoin",
    "space",
    "finance",
]

# Google Trends timeframe — "now 7-d" = last 7 days
TREND_TIMEFRAME = "now 7-d"

# Reddit subreddits to scrape for hot posts (no auth required)
REDDIT_SUBREDDITS = [
    "technology",       # IT general
    "artificial",       # AI general
    "MachineLearning",  # AI research
    "netsec",           # Security / offensive
    "cybersecurity",    # Security / defensive
    "ethereum",         # Blockchain
    "Bitcoin",          # Blockchain
]

# Maximum Reddit posts to fetch per subreddit
MAX_REDDIT_PER_SUB = 5

# Maximum GitHub trending repos to fetch per run
MAX_GITHUB_REPOS = 10

# Maximum Lobste.rs articles to fetch per run
MAX_LOBSTERS_ARTICLES = 10

# ---------------------------------------------------------------------------
# Article resume / full-body content
# ---------------------------------------------------------------------------

# Max paragraphs extracted from a downloaded .md file for the Altervista page
MAX_RESUME_PARAGRAPHS = 8

# Max words in the long-form resume generated by the LLM for the Altervista page
MAX_RESUME_WORDS = 500

# ---------------------------------------------------------------------------
# Pexels — cover image for the newsletter
# ---------------------------------------------------------------------------

# Get a free API key at https://www.pexels.com/api/
PEXELS_API_KEY = os.environ.get("PEXELS_API_KEY", "")

# ---------------------------------------------------------------------------
# Altervista WordPress — newsletter publishing
# ---------------------------------------------------------------------------

ALTERVISTA_SITE_URL              = os.environ.get("ALTERVISTA_SITE_URL", "").rstrip("/")
ALTERVISTA_USERNAME              = os.environ.get("ALTERVISTA_USERNAME", "")
ALTERVISTA_APP_PASSWORD          = os.environ.get("ALTERVISTA_APP_PASSWORD", "")
# Optional: pin the parent Newsletter page ID to skip auto-discovery
ALTERVISTA_NEWSLETTER_PAGE_ID    = os.environ.get("ALTERVISTA_NEWSLETTER_PAGE_ID", "")

# ---------------------------------------------------------------------------
# Bowl of Data website (Netlify)
# ---------------------------------------------------------------------------

# Set this in .env to enable Netlify anchor URL backfill in summaries JSON and
# news_*.md after running `python -m maki_newsletter.generate`.
# Example: NETLIFY_SITE_URL=https://bowlofdata.netlify.app
NETLIFY_SITE_URL = os.environ.get("NETLIFY_SITE_URL", "").rstrip("/")

# ---------------------------------------------------------------------------
# Output
# ---------------------------------------------------------------------------

OUTPUT_DIR = "output"
ARTICLES_DIR = "output/articles"

# ---------------------------------------------------------------------------
# Model release monitoring — AI provider announcement pages
# ---------------------------------------------------------------------------

MODEL_RELEASE_SOURCES = {
    "Anthropic":        "https://www.anthropic.com/news",
    "OpenAI":           "https://openai.com/news/",
    "xAI (Grok)":       "https://x.ai/news",
    "Google DeepMind":  "https://deepmind.google/discover/blog/",
    "Google Gemini":    "https://ai.google.dev/gemini-api/docs/models/gemini",
    "DeepSeek":         "https://api-docs.deepseek.com/updates",
    "Qwen (Alibaba)":   "https://qwenlm.github.io/",
    "Kimi (Moonshot)":  "https://kimi.moonshot.cn/",
    "GLM (THUDM)":      "https://chatglm.cn/",
    "Mistral":          "https://mistral.ai/news/",
    "Meta (Llama)":     "https://github.com/meta-llama/llama-models/releases",
    "Cohere":           "https://cohere.com/blog",
    "Amazon (Nova)":    "https://aws.amazon.com/blogs/machine-learning/",
    "Microsoft (Phi)":  "https://azure.microsoft.com/en-us/blog/topic/ai/",
    "Hugging Face":     "https://huggingface.co/blog",
}

# Max characters of page content sent to the model_releases_agent per provider
MAX_MODEL_RELEASE_CHARS = 8000
